//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.06 at 12:29:32 GMT+05:00 
//


package com.i2c.component.screenxmlobjects;


/**
 * Java content class for ControlType complex type.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/ScreensSchema.xsd line 64)
 * <p>
 * <pre>
 * &lt;complexType name="ControlType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="type" type="{http://www.ibm.com}UIType"/>
 *         &lt;element name="mapping_db_key" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="control-query" type="{http://www.ibm.com}ControlQueryType" minOccurs="0"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 */
public interface ControlType {


    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getType();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setType(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getMappingDbKey();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setMappingDbKey(java.lang.String value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link com.i2c.component.screenxmlobjects.ControlQueryType}
     */
    com.i2c.component.screenxmlobjects.ControlQueryType getControlQuery();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link com.i2c.component.screenxmlobjects.ControlQueryType}
     */
    void setControlQuery(com.i2c.component.screenxmlobjects.ControlQueryType value);

    /**
     * 
     * @return
     *     possible object is
     *     {@link java.lang.String}
     */
    java.lang.String getName();

    /**
     * 
     * @param value
     *     allowed object is
     *     {@link java.lang.String}
     */
    void setName(java.lang.String value);

}
