//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v1.0.2-b15-fcs 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2005.10.06 at 12:29:32 GMT+05:00 
//


package com.i2c.component.screenxmlobjects;


/**
 * Java content class for Screen element declaration.
 * <p>The following schema fragment specifies the expected content contained within this java content object. (defined at file:/C:/ScreensSchema.xsd line 17)
 * <p>
 * <pre>
 * &lt;element name="Screen" type="{http://www.ibm.com}ScreenType"/>
 * </pre>
 * 
 */
public interface Screen
    extends javax.xml.bind.Element, com.i2c.component.screenxmlobjects.ScreenType
{


}
